version: '3.4'

services:

  stix:
    image: ${DOCKER_REGISTRY-}stix
    networks:
    - stix_network
    build:
      context: .
      dockerfile: Stix/Dockerfile
      
  stix_mongo_api:
    image: ${DOCKER_REGISTRY-}stixmongoapi
    networks:
    - stix_network
    build:
      context: .
      dockerfile: Stix_Mongo_API/Dockerfile

networks:
    stix_network:
    
