version: '3.4'

services:

  stix:
    image: ${DOCKER_REGISTRY-}stix
    networks:
    - stix_network
    build:
      context: .
      dockerfile: Stix/Dockerfile
      
  stix_mongo_api:
    image: ${DOCKER_REGISTRY-}stixmongoapi
    networks:
    - stix_network
    build:
      context: .
      dockerfile: Stix_Mongo_API/Dockerfile
      
  mongodb:
    image: mongo:latest
    container_name: Stix-Mongo
    networks:
    - stix_network
    ports:
      - "27017:27017"
    depends_on:
      - "stix"

networks:
    stix_network:
    
