USE Netflix

INSERT INTO Subscription(subscription_name, price)
SELECT N'SD', 7.99
UNION ALL
SELECT N'HD', 10.99
UNION ALL
SELECT N'UHD', 13.99
UNION ALL
GO

insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Sigmund', '1/10/2022', 76, 65);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Emily', '7/23/2021', 89, 89);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Byram', '4/9/2022', 89, 79);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Weston', '4/17/2022', 7, 29);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Elston', '10/21/2021', 46, 61);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Gerty', '3/4/2022', 81, 16);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Damon', '3/10/2022', 70, 85);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Trix', '4/20/2022', 63, 92);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Kirsti', '4/24/2022', 7, 71);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Hyacintha', '12/5/2021', 70, 20);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Alvie', '5/10/2022', 70, 79);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Lovell', '2/4/2022', 10, 31);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Ellis', '3/17/2022', 39, 6);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Thorn', '7/22/2021', 14, 85);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Anthea', '6/8/2022', 77, 76);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Dale', '10/1/2021', 14, 8);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Obie', '6/25/2021', 45, 96);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Todd', '8/8/2021', 21, 66);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Ardella', '6/30/2021', 86, 70);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Ari', '6/5/2022', 38, 64);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Abdel', '7/21/2021', 26, 58);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Lonnie', '3/30/2022', 23, 42);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Eddy', '5/31/2022', 17, 17);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Humbert', '11/10/2021', 99, 32);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Nat', '12/29/2021', 54, 99);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Mendy', '1/9/2022', 70, 41);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Clea', '5/12/2022', 65, 5);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Eddie', '10/7/2021', 73, 42);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Conchita', '7/12/2021', 57, 40);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Hedy', '6/9/2022', 39, 59);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Fonzie', '5/11/2022', 71, 96);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Richie', '10/3/2021', 55, 88);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Carney', '7/24/2021', 2, 69);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Kristan', '7/10/2021', 35, 42);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Quintilla', '12/19/2021', 99, 22);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Roxine', '5/12/2022', 95, 56);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Christoffer', '2/3/2022', 27, 76);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Karyl', '6/29/2021', 61, 30);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Muffin', '9/15/2021', 67, 27);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Eduardo', '4/9/2022', 96, 80);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Lars', '7/8/2021', 94, 96);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Jeanne', '2/22/2022', 30, 57);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Caresa', '10/17/2021', 18, 44);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Napoleon', '10/28/2021', 91, 72);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Annetta', '9/10/2021', 44, 60);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Feliks', '9/27/2021', 19, 58);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Una', '9/3/2021', 38, 68);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Nani', '12/29/2021', 66, 64);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Yule', '1/29/2022', 98, 46);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Sibby', '11/5/2021', 23, 57);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Ken', '4/24/2022', 79, 64);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Todd', '6/20/2021', 69, 70);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Katusha', '4/11/2022', 28, 31);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Mohandis', '6/27/2021', 82, 10);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Edee', '8/3/2021', 35, 23);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Jonie', '4/30/2022', 48, 14);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Mauricio', '4/13/2022', 89, 89);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Farleigh', '7/26/2021', 50, 87);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Madeleine', '1/21/2022', 34, 10);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Bernetta', '4/27/2022', 70, 94);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Salvidor', '6/20/2021', 8, 10);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Benedikta', '9/27/2021', 7, 48);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Dietrich', '11/9/2021', 79, 41);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Ned', '4/13/2022', 68, 3);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Alvera', '8/1/2021', 66, 42);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Dukie', '4/20/2022', 79, 55);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Sigvard', '1/26/2022', 7, 9);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Giffie', '9/27/2021', 23, 22);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Gustave', '1/28/2022', 70, 64);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Thadeus', '7/23/2021', 20, 66);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Gunilla', '1/12/2022', 79, 98);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Issie', '4/25/2022', 17, 40);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Samuele', '11/15/2021', 95, 16);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Lorilee', '8/22/2021', 55, 81);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Shae', '10/24/2021', 83, 96);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Fairlie', '6/1/2022', 76, 92);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Prent', '7/28/2021', 97, 91);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Kathe', '4/11/2022', 88, 48);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Joseph', '12/5/2021', 42, 12);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Verna', '5/22/2022', 43, 63);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Marleah', '8/3/2021', 9, 20);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Ulrica', '6/2/2022', 56, 24);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Lory', '3/3/2022', 25, 12);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Antonietta', '3/20/2022', 82, 85);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Lora', '8/10/2021', 53, 1);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Mendy', '3/12/2022', 1, 11);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Garreth', '8/17/2021', 32, 35);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Bobbette', '4/4/2022', 15, 72);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Kit', '6/21/2021', 10, 85);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Shanna', '8/29/2021', 95, 83);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Alwin', '3/6/2022', 74, 85);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Astra', '5/9/2022', 6, 7);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Erny', '12/11/2021', 28, 61);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Gasparo', '5/3/2022', 94, 34);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Kristian', '6/15/2022', 46, 99);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Gwennie', '1/13/2022', 83, 67);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Felicia', '4/29/2022', 93, 30);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Karalee', '6/7/2022', 36, 23);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Dur', '11/27/2021', 25, 53);
insert into Profile (profile_name, date_of_birth, user_id, language_id) values ('Morris', '2/5/2022', 84, 14);
insert into Subtitle (language_id, cinema_id, subtitle_text) values (19, 69, 'Phasellus id sapien in sapien iaculis congue.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (97, 55, 'Donec vitae nisi.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (81, 58, 'Nulla suscipit ligula in lacus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (49, 47, 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (82, 19, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (6, 27, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (82, 36, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (41, 62, 'Suspendisse ornare consequat lectus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (78, 15, 'Suspendisse potenti.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (98, 1, 'Fusce consequat.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (40, 31, 'Etiam vel augue.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (36, 43, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (25, 32, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (75, 33, 'Suspendisse ornare consequat lectus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (50, 51, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (2, 1, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (79, 67, 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (94, 22, 'Etiam justo. Etiam pretium iaculis justo.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (74, 34, 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (62, 20, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (21, 36, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (34, 62, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (71, 31, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (29, 45, 'Pellentesque viverra pede ac diam.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (39, 77, 'Aenean lectus. Pellentesque eget nunc.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (59, 2, 'In hac habitasse platea dictumst.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (32, 21, 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (92, 81, 'Nunc purus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (49, 24, 'Proin at turpis a pede posuere nonummy.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (21, 57, 'Donec posuere metus vitae ipsum.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (85, 91, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (25, 55, 'In sagittis dui vel nisl. Duis ac nibh.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (95, 76, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (88, 98, 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (99, 74, 'Vestibulum sed magna at nunc commodo placerat.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (6, 15, 'Pellentesque ultrices mattis odio.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (26, 44, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (97, 47, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (13, 18, 'Aliquam non mauris.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (16, 48, 'Nulla mollis molestie lorem.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (64, 73, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (12, 61, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (26, 53, 'Duis mattis egestas metus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (85, 87, 'Vestibulum rutrum rutrum neque.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (43, 63, 'Sed ante.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (19, 94, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (46, 90, 'Mauris sit amet eros.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (78, 45, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (84, 64, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (42, 92, 'Donec ut mauris eget massa tempor convallis.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (99, 58, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (72, 67, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (7, 23, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (69, 40, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (15, 75, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (28, 8, 'Etiam justo. Etiam pretium iaculis justo.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (17, 62, 'Aenean fermentum.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (26, 41, 'Duis ac nibh.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (71, 13, 'Nullam porttitor lacus at turpis.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (66, 100, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (51, 36, 'Praesent blandit. Nam nulla.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (36, 85, 'Duis aliquam convallis nunc.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (11, 1, 'Nullam porttitor lacus at turpis.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (46, 66, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (90, 38, 'Ut tellus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (49, 49, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (88, 91, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (95, 90, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (8, 20, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (32, 61, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (90, 54, 'Vivamus tortor.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (50, 29, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (51, 53, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (97, 76, 'Nulla tempus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (61, 18, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (24, 26, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (45, 60, 'Aliquam erat volutpat. In congue.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (8, 54, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (18, 39, 'Ut at dolor quis odio consequat varius.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (34, 72, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (79, 2, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (98, 55, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (71, 44, 'Morbi non quam nec dui luctus rutrum.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (12, 19, 'Morbi non quam nec dui luctus rutrum.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (33, 67, 'Nulla facilisi.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (53, 26, 'Nullam varius.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (31, 46, 'In hac habitasse platea dictumst.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (19, 65, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (40, 64, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (55, 25, 'Donec posuere metus vitae ipsum.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (100, 61, 'Vestibulum rutrum rutrum neque.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (79, 28, 'Nulla ut erat id mauris vulputate elementum.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (80, 30, 'Morbi a ipsum. Integer a nibh.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (66, 81, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (67, 57, 'Aenean sit amet justo.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (51, 85, 'Nulla tellus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (2, 78, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (100, 76, 'Aliquam non mauris.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (31, 12, 'Suspendisse ornare consequat lectus.');
insert into Subtitle (language_id, cinema_id, subtitle_text) values (61, 34, 'Etiam justo.');

insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Ten Minutes Older', 'Corros 1st deg mult sites of unsp low limb, ex ank/ft, sqla', '3:32', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Safe Men', 'Other specified injury of left vertebral artery, subs encntr', '1:08', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Last Vegas', 'Poisoning by oth antidysrhythmic drugs, assault, subs encntr', '2:24', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Catch Me If You Can', 'Retinal vasculitis, left eye', '1:02', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Fires on the Plain (Nobi)', 'Embolism due to internal orthopedic prosth dev/grft, subs', '1:11', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Easy Wheels', 'Unspecified cirrhosis of liver', '1:47', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Secret of Moonacre, The', 'Unsp fracture of unsp acetabulum, init for opn fx', '3:34', 'Ut at dolor quis odio consequat varius.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Tomorrow at Dawn (Demain dès l''aube)', 'Malignant neoplasm of lower-inner quadrant of breast, female', '3:36', 'Morbi a ipsum.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Women, The', 'Other bursal cyst, unspecified hand', '1:54', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Chasing Sleep', 'Traum rupt of collat ligmt of r rng fngr at MCP/IP jt, init', '2:25', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Streets of Blood', 'Thrombosis of cardiac and vascular prosth dev/grft', '2:28', 'Aliquam erat volutpat.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Azur & Asmar (Azur et Asmar)', 'Congenital dislocation of hip, bilateral', '1:51', 'Proin risus. Praesent lectus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Stick It', 'Adverse effect of antiallergic and antiemetic drugs, init', '3:21', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Antz', 'Drown due to oth accident to sailboat, init', '3:18', 'Suspendisse potenti.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Seance on a Wet Afternoon', 'Other pneumothorax and air leak', '3:02', 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Shaft in Africa', 'Major laceration of left external jugular vein, subs encntr', '2:29', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Breakin'' 2: Electric Boogaloo', 'Displ transverse fx shaft of r ulna, 7thG', '2:18', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Period of Adjustment', 'Inj axillary or brachial vein, unsp side, init encntr', '1:39', 'Nulla facilisi.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Story of Yonosuke, A (Yokomichi Yonosuke)', 'Acute promyelocytic leukemia, in remission', '1:32', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Night Walker, The', 'Nondisp fx of olecran pro w intartic extn unsp ulna, sequela', '1:05', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Librarian, The: The Curse of the Judas Chalice', 'Osteolysis, other site', '3:12', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Earthling, The', 'Insect bite (nonvenomous) of right little finger, init', '3:14', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Tale of Cinema (Geuk jang jeon)', 'Occup of hv veh inj pick-up truck, pk-up/van in traf, subs', '2:19', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Don''t Go Breaking My Heart (Daan gyun naam yu)', 'Atrophy of globe, right eye', '1:05', 'Duis at velit eu est congue elementum.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Hawks and Sparrows (Uccellacci e Uccellini)', 'Poisoning by loop diuretics, undetermined, initial encounter', '2:13', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Love Me If You Dare (Jeux d''enfants)', 'Kearns-Sayre syndrome, bilateral', '3:00', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Aeon Flux', 'Activities w roller coasters and oth types of extrn motion', '2:22', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('She''s Out of My League', 'Laceration w/o foreign body of unsp shoulder, subs encntr', '3:20', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Levitated Mass', 'Chronic gingivitis, non-plaque induced', '3:42', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Girlhood', 'Poisoning by smallpox vaccines, undetermined, init encntr', '2:20', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Loser', 'War op w explosn due to acc disch of own munit, milt, init', '2:43', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Unzipped', 'Occup of hv veh injured in collision w hv veh nontraf, subs', '1:19', 'Integer ac neque.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Kicking & Screaming', 'Biotinidase deficiency', '3:25', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Twice in a Lifetime', 'Displ suprcndl fx w/o intrcndl extn low end unsp femr, 7thN', '1:20', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Kiss and Tell', 'Fall into natrl body of water strk surfc cause oth inj, sqla', '1:53', 'Donec dapibus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Confessions of a Burning Man', 'Posterior subcapsular polar age-related cataract, right eye', '2:10', 'Integer ac neque.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Finances of the Grand Duke, The (Die Finanzen des Großherzogs)', 'Valgus deformity, not elsewhere classified, left elbow', '2:55', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Stoned', 'Poisoning by phenothiaz antipsychot/neurolept, acc, subs', '2:07', 'Proin eu mi. Nulla ac enim.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Bang, Bang, You''re Dead', 'Traum rupt of volar plate of r idx fngr at MCP/IP jt, subs', '2:10', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Risky Business', 'Laceration w fb of unsp great toe w damage to nail, init', '3:19', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Hell', 'Oth osteoporosis w current pathological fracture, r forearm', '2:46', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Wesley Willis: The Daddy of Rock ''n'' Roll', 'Nondisp fx of med condyle of l tibia, 7thC', '3:19', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Three Brave Men', 'Unspecified dislocation of left index finger, init encntr', '3:16', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Milka - A Film About Taboos (Milka - elokuva tabuista)', 'Leucocoria, bilateral', '3:06', 'Morbi porttitor lorem id ligula.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Ong-Bak 3: The Final Battle (Ong Bak 3)', 'Laceration of unspecified renal vein, initial encounter', '3:28', 'Proin risus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('All Dogs Go to Heaven', 'Unspecified injury to sacral spinal cord, sequela', '2:47', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Lianna', 'Abn lev substnc nonmed source in specmn from oth org/tiss', '2:05', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Quatsch und die Nasenbärbande', 'Hit by falling object due to accident to fishing boat, subs', '1:12', 'Ut at dolor quis odio consequat varius.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Vitus', 'Legal intervnt involving oth sharp objects, suspect injured', '1:01', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Comancheros, The', 'Sltr-haris Type IV physl fx lower end ulna, right arm, init', '3:31', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('King and the Clown, The (Wang-ui namja)', 'Poisoning by oth anti-cmn-cold drugs, accidental', '2:22', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Muppet Musicians of Bremen, The', 'Nondisp fx of prox phalanx of r great toe, 7thD', '2:12', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Arrapaho', 'Displaced apophyseal fracture of unspecified femur', '1:17', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Last Exorcism, The', 'Oth fx shaft of unsp femr, 7thQ', '1:27', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Thief of Damascus', 'Acquired absence of unspecified upper limb below elbow', '2:52', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Ben', 'Displ commnt fx shaft of ulna, unsp arm, 7thC', '1:38', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Coronado', 'Familial chondrocalcinosis, multiple sites', '3:26', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Outlaw', 'Drown due to unsp watercraft overturning, init', '2:58', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Watcher, The', 'Unspecified physeal fracture of right  metatarsal, sequela', '2:50', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Chapman Report, The', 'Unsp intracap fx r femr, 7thR', '1:39', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Life and Debt', 'Other specified arthritis, hand', '1:28', 'In quis justo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('WolfCop', 'Other disorders of iris and ciliary body', '2:41', 'Maecenas pulvinar lobortis est.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Ocean''s Thirteen', 'Oth physeal fx lower end of r femur, subs for fx w nonunion', '1:39', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Hype!', 'Motorcycle rider (driver) injured in unsp nontraf', '1:39', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Wild Side', 'Toxic effect of unsp inorganic substance, undetermined', '1:26', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Rock-A-Doodle', 'Complete uterovaginal prolapse', '3:41', 'Vestibulum sed magna at nunc commodo placerat.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Babe, The', 'Other ovarian cyst, unspecified side', '1:54', 'Pellentesque at nulla.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('The Last Diamond', 'Fracture of one rib, right side, subs for fx w nonunion', '1:02', 'Pellentesque viverra pede ac diam.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('State of Play', 'Jump/div into swimming pool strk bottom causing oth injury', '1:01', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('House of Sand (Casa de Areia)', 'Other specified polyneuropathies', '3:18', 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Costa Brava', 'Displ intertroch fx unsp femr, subs for clos fx w delay heal', '2:34', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Beast, The', 'Oth injury of unsp tibial artery, left leg, subs encntr', '1:35', 'Nulla tempus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Ultramarines: A Warhammer 40,000 Movie', 'Other types of follicular lymphoma, intrapelvic lymph nodes', '1:53', 'Quisque ut erat.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Experience, The (Tadjrebeh)', 'Hyperventilation', '1:33', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('13 Assassins (Jûsan-nin no shikaku)', 'Corrosion w resulting rupture and dest of unsp eyeball, init', '1:02', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('The Seven-Ups', 'Burn of cornea and conjunctival sac, right eye, init encntr', '3:31', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('The Fox and the Hound 2', 'Torus fx upper end of unsp fibula, subs for fx w routn heal', '1:01', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('From Above', 'Poisoning by beta-adrenocpt antagonists, self-harm, subs', '3:37', 'Nulla nisl. Nunc nisl.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Amsterdamned', 'Oth fx of lower end unsp radius, subs for clos fx w malunion', '1:38', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Wood & Stock: Sexo, Orégano e Rock''n''Roll', 'Other intracranial (nontraumatic) hemorrhages of newborn', '1:58', 'Integer ac neque.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Knockin'' on Heaven''s Door', 'Burn of third degree of left palm, sequela', '2:11', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('National Theatre Live: Frankenstein', 'Retinal micro-aneurysms, unspecified', '1:00', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('This Property is Condemned', 'Varus deformity, not elsewhere classified, unspecified elbow', '2:54', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Battle of Britain', 'Corrosion of first degree of chin, initial encounter', '1:46', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Daybreak', 'Toxic effect of unsp pesticide, self-harm, sequela', '1:42', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('DysFunktional Family', 'Diffuse TBI w loss of consciousness of 30 minutes or less', '2:45', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('The Crowded Sky', 'Street, highway and other paved roadways as place', '1:14', 'Morbi a ipsum. Integer a nibh. In quis justo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Tank Girl', 'Malignant melanoma of skin of breast', '2:31', 'Aliquam erat volutpat.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Flight of the Intruder', 'Displ seg fx shaft of unsp femr, 7thR', '2:07', 'Maecenas pulvinar lobortis est.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Dreamlife of Angels, The (Vie rêvée des anges, La)', 'Corrosion of unsp deg mult sites of left wrist and hand', '2:14', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Godzilla 1985: The Legend Is Reborn (Gojira) (Godzilla) (Return of Godzilla, The)', 'Torus fracture of lower end of unsp ulna, init for clos fx', '3:14', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Everything Must Go', 'Oth ultralt/microlt/pwr-glider acc inj occupant, sequela', '2:46', 'Fusce posuere felis sed lacus.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Shadows of a Hot Summer (Stíny horkého léta)', 'Osteitis condensans, unspecified lower leg', '1:40', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Frozen Hell (Jäämarssi) ', 'Aphakia, right eye', '1:19', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Living Free', 'Displaced transverse fracture of shaft of right tibia, init', '2:15', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Midnight Crossing', 'Minor laceration of tail of pancreas', '1:14', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Vice Versa', 'Amblyopia suspect, left eye', '1:54', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Nun, The (La monja) ', 'Contact with workbench tool, initial encounter', '2:29', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Queen Christina', 'Injury of musculocutaneous nerve, right arm', '2:23', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Cinema (cinema_name, cinema_description , duration, credits) values ('Pleasure Party (Partie de plaisir, Une) (Piece of Pleasure, A)', 'Contusion of thoracic trachea, initial encounter', '1:10', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');

insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (1, 'ncraigg0@cyberchimps.com', '7X1XTvTkQ', 1, 1, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (2, 'ssorensen1@1und1.de', 'zsqhqDXY', 0, 1, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (3, 'ydickens2@earthlink.net', 'AHVV3Cd', 4, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (4, 'gmcilenna3@amazon.com', '0drMcsTHICvB', 2, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (5, 'jadamini4@google.pl', 'SnBJMF7T9', 1, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (6, 'hpettingill5@cocolog-nifty.com', 'zpB2mKDq', 3, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (7, 'rsamsworth6@slate.com', 'JY8SxciBsk0b', 1, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (8, 'dcorteney7@elpais.com', 'sXfrCjSeV', 4, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (9, 'owheatcroft8@wiley.com', 'YCmyFe', 0, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (10, 'kwhitley9@washington.edu', 'QUdjZgkRd2', 3, 0, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (11, 'rdalgarnochta@etsy.com', 'Pk8IsjJv8', 3, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (12, 'cboycottb@nba.com', 'llZ4zu', 0, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (13, 'nbonseyc@freewebs.com', 'GBlg2ihb0Qw', 4, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (14, 'jholbarrowd@businesswire.com', '4Wo8wTl', 0, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (15, 'mdarrigoe@delicious.com', 'm9JNXQ', 2, 0, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (16, 'tbellsonf@pen.io', 'va6xi6849', 4, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (17, 'akayzerg@ezinearticles.com', 'w2DHqS6M', 0, 1, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (18, 'cjordih@imageshack.us', '4wTYxc0B', 4, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (19, 'kcaproni@ameblo.jp', '0EOIbvV', 3, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (20, 'shucksteppj@statcounter.com', 'b9I3d5', 0, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (21, 'kmilnek@ovh.net', 'IJZUwQ7AU', 3, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (22, 'eivachyovl@bloomberg.com', 'Z4HfuD', 3, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (23, 'mvittorem@alexa.com', 'b7HsnJhzcz', 4, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (24, 'athickinn@guardian.co.uk', 'QhLuGSuO', 4, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (25, 'rbilletto@aol.com', 'zmB0Frrda', 1, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (26, 'tmcgerrp@engadget.com', 'vKacPtfiW', 3, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (27, 'yurwenq@tmall.com', 'gqZsYMuioH8', 2, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (28, 'mklemzr@sourceforge.net', 'rNTYPurS3', 0, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (29, 'pbogarts@japanpost.jp', 'JXXmcvpIBQHJ', 4, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (30, 'kjouanetont@pen.io', 'eZI3uNdk3', 4, 0, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (31, 'bgerneru@odnoklassniki.ru', 'zyCU1k', 0, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (32, 'couldv@princeton.edu', 'UdnwnE', 3, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (33, 'rbotleyw@acquirethisname.com', '4VYvdjS0d', 4, 1, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (34, 'pabsonx@salon.com', 'HJVMW8', 3, 1, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (35, 'hfoskiny@domainmarket.com', 'A1c8vN', 3, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (36, 'kcrightonz@ameblo.jp', 'hqJuSRV', 2, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (37, 'abasketfield10@baidu.com', '1IBJuE5Mb', 3, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (38, 'bpavlitschek11@tripadvisor.com', 'YkMrw7UHJI67', 0, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (39, 'kivins12@addtoany.com', 'JNaQgIii7', 3, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (40, 'efitzsimons13@biglobe.ne.jp', 'l4qfY56', 3, 1, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (41, 'sleggin14@wikipedia.org', 'YKbmxw6', 4, 1, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (42, 'cduesbury15@ameblo.jp', '3sECRGIZ6Uv', 3, 1, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (43, 'leagles16@etsy.com', '0jsrM6GC2nAq', 3, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (44, 'mwhyborne17@wufoo.com', 'umTPwVf8W7k', 1, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (45, 'ljoddens18@lulu.com', 'OakW7tMf29', 2, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (46, 'kstedall19@whitehouse.gov', 'IbUnJvA', 1, 0, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (47, 'nzappel1a@shinystat.com', 'JTyBY8TFPEPI', 4, 1, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (48, 'ttwinborne1b@instagram.com', '5riqiOQ', 0, 0, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (49, 'wemney1c@miitbeian.gov.cn', 'sJConBM5d6', 2, 0, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (50, 'bjerrems1d@creativecommons.org', 'sIgMAn', 1, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (51, 'nscheffel1e@nydailynews.com', 'zOw6QR', 1, 1, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (52, 'mipplett1f@123-reg.co.uk', 'btG3tS7l', 3, 1, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (53, 'agarlant1g@aboutads.info', 'nW0ubwD6UHH9', 1, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (54, 'trapport1h@rambler.ru', 'i2ojsdRUN4', 2, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (55, 'jsherbrook1i@flavors.me', 'gIZqCzb', 1, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (56, 'jweippert1j@reverbnation.com', 'A8Zi5hBBSz', 3, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (57, 'akears1k@trellian.com', 'EB0zhxyf', 4, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (58, 'mlinklet1l@chicagotribune.com', '5Tedd9J2R', 0, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (59, 'ppetrozzi1m@surveymonkey.com', '4t2OF8', 4, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (60, 'gradke1n@marriott.com', 'PYFbGd', 0, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (61, 'lwoolerton1o@goodreads.com', 'Xdc5PPKqd', 4, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (62, 'scowdery1p@com.com', 'nluHlCB5AQCx', 3, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (63, 'dmaine1q@issuu.com', 'GAnqPtNv', 2, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (64, 'gwalsom1r@merriam-webster.com', 'ZuDk9He2', 0, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (65, 'jjorin1s@marriott.com', 'To713d', 3, 1, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (66, 'holifard1t@indiatimes.com', '25ql61SCqpg9', 2, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (67, 'bsackett1u@state.tx.us', 'yTTG55h', 1, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (68, 'mmaryman1v@dmoz.org', 'EAR1inmBkIR', 1, 1, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (69, 'gpeterson1w@tripod.com', 'nXvkpM', 0, 0, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (70, 'wclardge1x@webmd.com', 'O99QgOkXU5PS', 2, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (71, 'fpilipets1y@zdnet.com', 'RJyiSP', 0, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (72, 'avince1z@npr.org', 'jF2WKk78W0', 1, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (73, 'abottrill20@github.io', 'pfFtdQbv', 0, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (74, 'bdennehy21@themeforest.net', 'IWbDMV3VQt', 0, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (75, 'hzolini22@si.edu', 'Qxi3Nc6Qy', 2, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (76, 'lvalance23@ucoz.com', 'k31FZNpI', 1, 1, 2);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (77, 'rfills24@csmonitor.com', 'TXF9GZ', 0, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (78, 'dtembey25@tripadvisor.com', 'PRr7BJluBg', 1, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (79, 'vhefferon26@noaa.gov', 'mbBD0MRM9', 1, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (80, 'acapner27@edublogs.org', '6vpsvhyci', 2, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (81, 'bphilip28@howstuffworks.com', 'UaAdp8', 0, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (82, 'rgiovannazzi29@microsoft.com', 'HvcZxAZPUT', 0, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (83, 'mdauby2a@hibu.com', 'ma4tGoHAhlkw', 2, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (84, 'jloges2b@wired.com', '5u7fqTkg', 3, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (85, 'spahler2c@disqus.com', 'qwNKWhY0R', 0, 1, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (86, 'nmatthews2d@drupal.org', 'mvVjdSIsqOr', 1, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (87, 'rthoma2e@macromedia.com', 'dYvOnwEQv', 1, 1, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (88, 'olumsdale2f@dyndns.org', 'wdLyje', 4, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (89, 'mhamnett2g@cafepress.com', '0kVWz4RAx', 2, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (90, 'bharber2h@ed.gov', '546Z9cUlooDk', 2, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (91, 'igergolet2i@amazon.co.jp', '9Zg4BHhO', 4, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (92, 'fissatt2j@wisc.edu', 'QBrbFc', 4, 1, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (93, 'emartschke2k@examiner.com', 'lgp78D', 1, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (94, 'gterzi2l@springer.com', 'hb9h2fYbpa', 3, 0, 1);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (95, 'jchivrall2m@noaa.gov', '9IESXgtB5', 4, 0, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (96, 'dwindrum2n@vistaprint.com', 'Fv4gH1hl', 4, 1, 3);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (97, 'acampey2o@yahoo.com', 'R8CqpQQss', 3, 0, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (98, 'krolley2p@yahoo.co.jp', 'VKHbg2', 0, 1, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (99, 'csealand2q@weather.com', 'ZTHhrz', 1, 1, null);
insert into User (user_id, user_email, user_password, login_attempts, is_blocked, subscription_id) values (100, 'frisborough2r@admin.ch', '4Oa5UJU2', 1, 0, 2);

insert into Language (language_name) values ('Portuguese');
insert into Language (language_name) values ('Montenegrin');
insert into Language (language_name) values ('Burmese');
insert into Language (language_name) values ('Azeri');
insert into Language (language_name) values ('Somali');
insert into Language (language_name) values ('Dutch');
insert into Language (language_name) values ('Latvian');
insert into Language (language_name) values ('Khmer');
insert into Language (language_name) values ('Danish');
insert into Language (language_name) values ('Tetum');
insert into Language (language_name) values ('Estonian');
insert into Language (language_name) values ('Malay');
insert into Language (language_name) values ('Hungarian');
insert into Language (language_name) values ('Maltese');
insert into Language (language_name) values ('German');
insert into Language (language_name) values ('Khmer');
insert into Language (language_name) values ('Dutch');
insert into Language (language_name) values ('Hiri Motu');
insert into Language (language_name) values ('Gujarati');
insert into Language (language_name) values ('Korean');
insert into Language (language_name) values ('Bislama');
insert into Language (language_name) values ('German');
insert into Language (language_name) values ('Afrikaans');
insert into Language (language_name) values ('Pashto');
insert into Language (language_name) values ('Zulu');
insert into Language (language_name) values ('Danish');
insert into Language (language_name) values ('Luxembourgish');
insert into Language (language_name) values ('Kazakh');
insert into Language (language_name) values ('Marathi');
insert into Language (language_name) values ('Luxembourgish');
insert into Language (language_name) values ('Croatian');
insert into Language (language_name) values ('Filipino');
insert into Language (language_name) values ('Pashto');
insert into Language (language_name) values ('Moldovan');
insert into Language (language_name) values ('Bulgarian');
insert into Language (language_name) values ('Ndebele');
insert into Language (language_name) values ('Moldovan');
insert into Language (language_name) values ('Northern Sotho');
insert into Language (language_name) values ('Guaraní');
insert into Language (language_name) values ('Belarusian');
insert into Language (language_name) values ('Kurdish');
insert into Language (language_name) values ('Maltese');
insert into Language (language_name) values ('Bengali');
insert into Language (language_name) values ('Czech');
insert into Language (language_name) values ('Belarusian');
insert into Language (language_name) values ('Greek');
insert into Language (language_name) values ('Haitian Creole');
insert into Language (language_name) values ('Luxembourgish');
insert into Language (language_name) values ('Bosnian');
insert into Language (language_name) values ('French');
insert into Language (language_name) values ('Spanish');
insert into Language (language_name) values ('Guaraní');
insert into Language (language_name) values ('Bislama');
insert into Language (language_name) values ('Catalan');
insert into Language (language_name) values ('Papiamento');
insert into Language (language_name) values ('Armenian');
insert into Language (language_name) values ('Haitian Creole');
insert into Language (language_name) values ('Hindi');
insert into Language (language_name) values ('Hiri Motu');
insert into Language (language_name) values ('Oriya');
insert into Language (language_name) values ('Azeri');
insert into Language (language_name) values ('Maltese');
insert into Language (language_name) values ('Marathi');
insert into Language (language_name) values ('Norwegian');
insert into Language (language_name) values ('Maltese');
insert into Language (language_name) values ('Malayalam');
insert into Language (language_name) values ('Kashmiri');
insert into Language (language_name) values ('Chinese');
insert into Language (language_name) values ('Northern Sotho');
insert into Language (language_name) values ('Macedonian');
insert into Language (language_name) values ('Armenian');
insert into Language (language_name) values ('Swedish');
insert into Language (language_name) values ('Khmer');
insert into Language (language_name) values ('Gagauz');
insert into Language (language_name) values ('Danish');
insert into Language (language_name) values ('Malagasy');
insert into Language (language_name) values ('Nepali');
insert into Language (language_name) values ('Norwegian');
insert into Language (language_name) values ('Lithuanian');
insert into Language (language_name) values ('Māori');
insert into Language (language_name) values ('Tajik');
insert into Language (language_name) values ('English');
insert into Language (language_name) values ('West Frisian');
insert into Language (language_name) values ('Moldovan');
insert into Language (language_name) values ('Telugu');
insert into Language (language_name) values ('Northern Sotho');
insert into Language (language_name) values ('Papiamento');
insert into Language (language_name) values ('Bulgarian');
insert into Language (language_name) values ('Romanian');
insert into Language (language_name) values ('Bengali');
insert into Language (language_name) values ('Chinese');
insert into Language (language_name) values ('Oriya');
insert into Language (language_name) values ('Croatian');
insert into Language (language_name) values ('Kashmiri');
insert into Language (language_name) values ('Hungarian');
insert into Language (language_name) values ('Tetum');
insert into Language (language_name) values ('Indonesian');
insert into Language (language_name) values ('New Zealand Sign Language');
insert into Language (language_name) values ('Oriya');
insert into Language (language_name) values ('Luxembourgish');
